// The crate-local clippy.toml files: what clippy-scopes.toml says each must be, and where the tree differs.
// Used by clippy-scopes.mjs (which writes them) and check-lint-config.mjs (which checks them).
import fs from 'node:fs';
import path from 'node:path';
import { readText, walk } from './_lib.mjs';
import { parseToml } from './_toml.mjs';

const HEADER = (crate, reason) =>
  `# Generated by scripts/clippy-scopes.mjs from the root clippy.toml minus clippy-scopes.toml [${crate}]:\n# ${reason}.\n# Do not edit: change the root file or clippy-scopes.toml and run \`node scripts/clippy-scopes.mjs --write\`.\n`;

const ENTRY = /^\s*\{\s*path\s*=\s*"([^"]+)"/;

/** The expected crate-local files, as { 'crates/<crate>/clippy.toml': text }, and problems with the declaration. */
export function expectedScopes(root) {
  const problems = [];
  const rootText = readText(path.join(root, 'clippy.toml'));
  const rootPaths = new Set(rootText.split('\n').map((l) => ENTRY.exec(l)?.[1]).filter(Boolean));
  const scopes = parseToml(readText(path.join(root, 'clippy-scopes.toml')), 'clippy-scopes.toml');
  const files = {};
  for (const [crate, scope] of Object.entries(scopes)) {
    const exempt = new Set(scope.exempt ?? []);
    if (!scope.reason) problems.push(`clippy-scopes.toml [${crate}] has no reason`);
    if (!fs.existsSync(path.join(root, 'crates', crate, 'Cargo.toml'))) problems.push(`clippy-scopes.toml [${crate}] names no crate under crates/`);
    for (const p of exempt) if (!rootPaths.has(p)) problems.push(`clippy-scopes.toml [${crate}] exempts ${p}, which the root clippy.toml does not ban`);
    const kept = rootText
      .split('\n')
      .filter((l) => !exempt.has(ENTRY.exec(l)?.[1]))
      .join('\n');
    files[`crates/${crate}/clippy.toml`] = HEADER(crate, scope.reason ?? '') + kept;
  }
  return { files, problems };
}

/** Every clippy.toml or .clippy.toml in the tree other than the root one, fixtures excluded. */
export function localClippyFiles(root) {
  return walk(root, (f) => /(^|\/)\.?clippy\.toml$/.test(f) && f !== 'clippy.toml' && !f.startsWith('scripts/fixtures/'));
}

export function checkScopes(root) {
  const { files, problems } = expectedScopes(root);
  const findings = [...problems];
  for (const f of localClippyFiles(root)) {
    if (!(f in files)) findings.push(`${f}: a clippy.toml clippy-scopes.toml does not declare (a crate-local file replaces the whole ban list)`);
  }
  for (const [f, text] of Object.entries(files)) {
    const full = path.join(root, f);
    if (!fs.existsSync(full)) findings.push(`${f}: missing; run node scripts/clippy-scopes.mjs --write`);
    else if (readText(full) !== text) findings.push(`${f}: differs from the root clippy.toml minus its declared exemptions; run node scripts/clippy-scopes.mjs --write`);
  }
  return findings;
}
