// Secrets: gitleaks (mise.toml pins it) over the files git would commit, tracked or untracked but not ignored,
// from the repository root, so a vendored project's root is read too; and, given a base, over every commit
// since it, so a secret added and removed inside one change is still refused. gitleaks reads ignored files
// when it is pointed at a directory, so the files are listed by git and copied under target/gitleaks first.
//
// The configuration is generated here, not read from the tree: gitleaks' own rules, plus one allowance for the
// sha256 hashes suppressions.txt lists. A `.gitleaks.toml` or `.gitleaksignore` in the tree is not read, and a
// `gitleaks:allow` comment does not hide a finding (--ignore-gitleaks-allow).
//
// First, two canaries: a generated file holding a GitHub token, marked `gitleaks:allow`, must be refused; and a
// throwaway repository whose one commit adds a token and whose next removes it must be refused over the range.
// Usage: node scripts/secrets.mjs [base-sha]
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { capture, captureAll, main, ok, run, Fail } from './_lib.mjs';

const repo = path.resolve(import.meta.dirname, '..');
const work = path.join(repo, 'target', 'gitleaks');
const config = path.join(work, 'config.toml');
const noIgnores = path.join(work, 'no-ignores');

const CONFIG = `# Generated by scripts/secrets.mjs. Not committed.
[extend]
useDefault = true

[[allowlists]]
description = "the sha256 hashes in suppressions.txt"
regexTarget = "match"
regexes = ['''sha256:[0-9a-f]{64}''']
`;

const gitleaks = (...args) =>
  captureAll('gitleaks', [...args, '--no-banner', '--redact', '--ignore-gitleaks-allow', '--config', config, '--gitleaks-ignore-path', noIgnores, '--exit-code', '1', '--log-level', 'warn', '--verbose']);

/** A token of the shape gitleaks' github-pat rule matches, fresh each run so nothing committed holds one. */
function token() {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  return `ghp_${[...crypto.randomBytes(36)].map((b) => alphabet[b % alphabet.length]).join('')}`;
}

function canaries() {
  const tree = path.join(work, 'canary', 'tree');
  fs.mkdirSync(tree, { recursive: true });
  fs.writeFileSync(path.join(tree, 'leak.rs'), `const TOKEN: &str = "${token()}"; // gitleaks:allow\n`);
  const dir = gitleaks('dir', tree);
  if (dir.status !== 1) throw new Fail(`gitleaks passed its canary, a token marked gitleaks:allow (exit ${dir.status}):\n${dir.stderr}`);

  const history = path.join(work, 'canary', 'history');
  fs.mkdirSync(history, { recursive: true });
  const git = (...args) => run('git', ['-c', 'user.name=canary', '-c', 'user.email=canary@example.invalid', '-c', 'commit.gpgsign=false', ...args], { cwd: history });
  git('init', '-q', '-b', 'main');
  fs.writeFileSync(path.join(history, 'README'), 'clean\n');
  git('add', '-A');
  git('commit', '-q', '-m', 'clean');
  const base = capture('git', ['rev-parse', 'HEAD'], { cwd: history });
  fs.writeFileSync(path.join(history, 'config.rs'), `const TOKEN: &str = "${token()}";\n`);
  git('add', '-A');
  git('commit', '-q', '-m', 'add a token');
  fs.rmSync(path.join(history, 'config.rs'));
  git('add', '-A');
  git('commit', '-q', '-m', 'remove it');
  const range = gitleaks('git', history, `--log-opts=${base}..HEAD`);
  if (range.status !== 1) throw new Fail(`gitleaks passed its canary, a token added and removed inside the range (exit ${range.status}):\n${range.stderr}`);
  console.log('gitleaks refused its canaries: a token marked gitleaks:allow, and a token added and removed in one range');
}

main(() => {
  const base = process.argv[2] ?? '';
  fs.rmSync(work, { recursive: true, force: true });
  fs.mkdirSync(noIgnores, { recursive: true });
  fs.writeFileSync(config, CONFIG);
  canaries();

  const top = capture('git', ['rev-parse', '--show-toplevel'], { cwd: repo });
  const listed = capture('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], { cwd: top }).split('\0').filter(Boolean);
  const tree = path.join(work, 'tree');
  let copied = 0;
  for (const rel of listed) {
    const from = path.join(top, rel);
    const stat = fs.lstatSync(from, { throwIfNoEntry: false });
    if (!stat?.isFile()) continue;
    fs.mkdirSync(path.dirname(path.join(tree, rel)), { recursive: true });
    fs.copyFileSync(from, path.join(tree, rel));
    copied += 1;
  }
  const scan = gitleaks('dir', tree);
  if (scan.status !== 0) {
    console.error(scan.stdout + scan.stderr);
    throw new Fail(`gitleaks found a secret in the files git would commit (exit ${scan.status}; paths above are relative to ${top})`, scan.status);
  }
  console.log(`gitleaks: no secret in the ${copied} files git would commit under ${top}`);

  if (!base || /^0+$/.test(base) || !ok('git', ['cat-file', '-e', `${base}^{commit}`], { cwd: top })) {
    console.log(`gitleaks: no base commit given or known, so no commit range is read (base ${base || 'not given'})`);
    return;
  }
  const range = gitleaks('git', top, `--log-opts=${base}..HEAD`);
  if (range.status !== 0) {
    console.error(range.stdout + range.stderr);
    throw new Fail(`gitleaks found a secret in a commit since ${base.slice(0, 12)} (exit ${range.status})`, range.status);
  }
  console.log(`gitleaks: no secret in any commit since ${base.slice(0, 12)}`);
});
